title: Mathilde Abel

nav:
  - name: "About"
    link: "/"
  - name: "Publications"
    link: "/publications"
  - name: "Teaching"
    link: "/teaching"
  - name: "Contact"
    link: "/contact"

footer:
  - name: "Email"
    link: "mailto:mathilde.abel@telecom-paris.fr"
  - name: "LinkedIn"
    link: "https://www.linkedin.com/in/mathilde-abel-4bb573197"
  - name: "GitHub"
    link: "https://github.com/mathildeabl"
  - name: "ORCID"
    link: "https://orcid.org/0000-0003-1467-12890"

remote_theme: ankitsultana/researcher@gem
